### ISSUE TITLE
some font not working whay?

### ISSUE THREAD

**Issue by idrisalshikh** [mpcabd/python-arabic-reshaper#25]
hi I try the example with attached font but the image show without text
[Uthmanic.zip](https://github.com/mpcabd/python-arabic-reshaper/files/2425636/Uthmanic.zip)
without reshaper 
![pil_text_font](https://user-images.githubusercontent.com/5154116/46170460-73684700-c2d0-11e8-8ba6-80f968fafa2b.png)
with reshaper 
![pil_text_font](https://user-images.githubusercontent.com/5154116/46170508-985cba00-c2d0-11e8-8682-d480706247cf.png)

**Comment by ravarage** [comment]
if you open your fonts with fontforge you will see with is wrong, your font use u0644.init u0644.zz04 instead of traditional known UTF 8 General standard , there are two ways to get your font to work 
first if we manage to python read after dot which something I wasnt able to do it 
second use Adobe glyph name which I have no Idea how that work but it seem more unique I dont know how to use it , but its make sense if we manage to it ,   Mr.Abdullah Diab is smart guy he might be able to it but you can use his code and what I told you to figure something out, I am also trying but I am not a pro

**Comment by ravarage** [comment]
you can install libraqm , and when you draw text , write direction = "rtl" and you wont need any tools 
for ubuntu based system this line will get the job done for you
sudo apt-get install libraqm-dev
for mac I think its almost the same 
but for windows you have to build it yourself
