### ISSUE TITLE
What need to do to stretch arabic text when synthetic text image ?

### ISSUE THREAD

**Issue by DeepInSearch** [mpcabd/python-arabic-reshaper#37]
When I use arabic font, I synthetic text image and get something like this:

> 
![testFiles_AljazeeraHD_vd14_frame_147-3](https://user-images.githubusercontent.com/18027375/74037088-89276980-49f8-11ea-87fc-6fdc5849e142.jpg)
while actually in video scene, the real image will be this:

> 
![AljazeeraHD_vd14_frame_147-3](https://user-images.githubusercontent.com/18027375/74037122-993f4900-49f8-11ea-9519-faf31e064e1d.png)
Do you know how can I stretch the arabic letter when I synthetic the text image ?
What should I do ?
Thanks !

**Comment by mpcabd** [comment]
Not sure about the context of your case, but in Unicode there is the letter [\u0640](https://www.fileformat.info/info/unicode/char/0640/index.htm) which when put between the letters will act as a stretcher, it can only be used between letters that already connect to each other.

Examples:

> مرحبا
> مــــــرحــــــبــــــــا

As you can see above, it can't stretch between ر and حـ because the letter ر doesn't connect to the letter that comes after it.

In all cases, this is not an issue in the reshaper, so I'd advise you to post such questions on SlackOverflow, or you could just message me directly.

Good luck.
