### ISSUE TITLE
font type not applied to image

### ISSUE THREAD

**Issue by mjhasani** [mpcabd/python-arabic-reshaper#64]
Hi 
I used reshaper library as below:

reshaper_ = arabic_reshaper.ArabicReshaper(
    arabic_reshaper.config_for_true_type_font(
        './path/to/font.ttf',
        arabic_reshaper.ENABLE_ALL_LIGATURES
    )
)
axis.set_title(reshaper_.reshape( title )[::-1] )

but the font not applied to image title.

**Comment by mpcabd** [comment]
Hello, the reshaper is not responsible for rendering anything, the option you used `config_for_true_type_font` is just so that the reshaper doesn't use glyphs that your font does not support. You still need to render the reshaped text using your font in whatever library you're using for rendering (matplotlib in your case).
